# Nord theme
# bg:
# - #2E3440
# - #3B4252
# - #434C5E
# - #4C566A

# fg:
# - #D8DEE9
# - #E5E9F0
# - #ECEFF4

# green-blue: #8FBCBB
# sky-blue:   #88C0D0
# frost-blue: #81A1C1
# dark-blue:  #5E81AC

# red:    #BF616A
# orange: #D08770
# yellow: #EBCB8B
# green:  #A3BE8C
# purple: #B48EAD

format = """
[](#D8DEE9)\
$username\
[](fg:#D8DEE9 bg:#4C566A)\
$directory\
[](fg:#4C566A bg:#EBCB8B)\
$git_branch\
$git_status\
[](fg:#EBCB8B bg:#86BBD8)\
$python\
$nodejs\
$terraform\
[ ](fg:#86BBD8)\
"""

right_format = """
[](#4C566A)\
$time\
[](fg:#4C566A)\
"""

# Disable the blank line at the start of the prompt
# add_newline = true

# You can also replace your username with a neat symbol like  to save some space
[username]
show_always = true
style_user = "fg:#2E3440 bg:#D8DEE9"
style_root = "fg:#D8DEE9 bg:#BF616A"
format = '[  ]($style)'

[directory]
style = "fg:#D8DEE9 bg:#4C566A"
format = "[ $path ]($style)"
truncation_length = 40
truncation_symbol = "…/"

# Here is how you can shorten some long paths by text replacement
# similar to mapped_locations in Oh My Posh:
[directory.substitutions]
"Documents" = " "
"Downloads" = " "
"Music" = " "
"Pictures" = " "
# Keep in mind that the order matters. For example:
# "Important Documents" = "  "
# will not be replaced, because "Documents" was already substituted before.
# So either put "Important Documents" before "Documents" or use the substituted version:
# "Important  " = "  "

[git_branch]
symbol = ""
style = "bg:#EBCB8B"
format = '[[ $symbol $branch ](fg:#2E3440 bg:#EBCB8B)]($style)'

[git_status]
style = "bg:#EBCB8B"
format = '[[($all_status$ahead_behind )](fg:#2E3440 bg:#EBCB8B)]($style)'

[nodejs]
symbol = ""
style = "bg:#86BBD8"
format = '[[ $symbol ($version) ](bg:#86BBD8)]($style)'

[time]
disabled = false
time_format = "%R" # Hour:Minute Format
style = "bg:#4C566A"
format = '[[   $time ](bg:#4C566A)]($style)'
